### ISSUE TITLE
Maximum line length is too low

### ISSUE THREAD

**Issue by koral--** [DroidsOnRoids/android-style-guide#1]
![image](https://cloud.githubusercontent.com/assets/3340954/25050435/bcfa67f8-2147-11e7-8dba-4216e4d3ab73.png)
@AlexKrupa  should we increase it to 140-150 perhaps?

**Comment by AlexKrupa** [comment]
My main reason against increasing it over current limit (120 characters) is that it forces horizontal scrolling during code review.

Other than that, it might make code harder to read/interpret - compare it to a book or an article.

**Comment by koral--** [comment]
It is not applicable to all screens, but fair enough. It seems that 120 is optimal for most of the screens used in a company.
